### ISSUE TITLE
GasLimit setting  in `default.js` doesn't affect to actual gas cost

### ISSUE THREAD

**Issue by churik** [status-im/autobounty#15]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: with `gasLimit: 0` in `default.js` contracts is still funded
#### Expected behavior
[comment]: # (Describe what you expected to happen.)
error in log

#### Actual behavior
[comment]: # (Describe what actually happened.)
Issue is funded successfully

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
**Requirements**: 
1) Repo is installed and configured for SOB.
2) Bot is installed and configured for repo.
3) `gasLimit: 0` in `default.js`
**Steps:**
- Create an issue
- Put bounty-size + bounty labels
- Wait until autobot will handle an issue

### Additional Information
[comment]: # (Were you using an Ethereum wallet connected to your browser (MetaMask/Parity chrome plugin). Or Mist?)
* Ethereum wallet used: Metamsk
[comment]: # (Browser and version)
* Browser: Chrome
* Log:
```
info: Handling https://api.github.com/repos/NewOrGanizationSOB/RepoSOB/issues/135
info: [OK] Succesfully funded bounty with transaction 0xc8836937bb7682b2e88bf6114716aeec2704f398251cc098301d1ee08c957df6
info:  * From: 0xcf2272205cc0cf96Cfbb9Dd740BD681D1E86901E
info:  * To: 0xc55cF4B03948D7EBc8b9E8BAD92643703811d162
info:  * Amount: 6000000000000000000
info:  * Gas Price: 1000000000
info: ====================================================
info: Issue well funded: https://api.github.com/repos/NewOrGanizationSOB/RepoSOB/issues/135
```

**Comment by andytudhope** [comment]
Thing work a little differently after Pedro and I fixed token sends. We are actually intercepting some stuff because of the way we need to sign things when sending some tokens, one of which is the gasPrice that we [pull automatically from the provider](https://github.com/status-im/autobounty/blob/master/bot/index.js#L170), which is clearly defaulting to `200000`. 

In the case of the tx above, you can see that it defaulted to `200000` gas, of which `90779` was used (the rest is returned to you). When we set it in `default.js`, it will only apply to ETH sends as it is currently set up.

https://ropsten.etherscan.io/tx/0xc8836937bb7682b2e88bf6114716aeec2704f398251cc098301d1ee08c957df6
